# Generated by Django 5.1.5 on 2026-04-13 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TowerGameScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(default='Anonymous', max_length=100)),
                ('moves', models.IntegerField()),
                ('difficulty', models.IntegerField(default=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Tower Game Score',
                'verbose_name_plural': 'Tower Game Scores',
                'ordering': ['moves', 'difficulty'],
            },
        ),
    ]
