# Generated by Django 5.1.5 on 2026-04-14 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('towerGame', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='towergamescore',
            options={'ordering': ['wasted_moves', 'difficulty'], 'verbose_name': 'Tower Game Score', 'verbose_name_plural': 'Tower Game Scores'},
        ),
        migrations.AddField(
            model_name='towergamescore',
            name='wasted_moves',
            field=models.IntegerField(default=2),
        ),
    ]
